name: frontend
description: A new Flutter project
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
