// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqeGlzpsh1z48e4SS9yT8WsURCdnSuve0',
    appId: '1:889197906931:web:2de730ef76a846a44be086',
    messagingSenderId: '889197906931',
    projectId: 'myrefrence-499b0',
    authDomain: 'myrefrence-499b0.firebaseapp.com',
    storageBucket: 'myrefrence-499b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSyHJ8dpQZ8haXpnACAYmI3BqzT0YJG7g',
    appId: '1:889197906931:android:6ed289b17cd761c54be086',
    messagingSenderId: '889197906931',
    projectId: 'myrefrence-499b0',
    storageBucket: 'myrefrence-499b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6a21LFoIXo9wC8uY6ITskm47nUr-uzpw',
    appId: '1:889197906931:ios:77fef9c2481b1e724be086',
    messagingSenderId: '889197906931',
    projectId: 'myrefrence-499b0',
    storageBucket: 'myrefrence-499b0.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6a21LFoIXo9wC8uY6ITskm47nUr-uzpw',
    appId: '1:889197906931:ios:77fef9c2481b1e724be086',
    messagingSenderId: '889197906931',
    projectId: 'myrefrence-499b0',
    storageBucket: 'myrefrence-499b0.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqeGlzpsh1z48e4SS9yT8WsURCdnSuve0',
    appId: '1:889197906931:web:371e309c94b8860e4be086',
    messagingSenderId: '889197906931',
    projectId: 'myrefrence-499b0',
    authDomain: 'myrefrence-499b0.firebaseapp.com',
    storageBucket: 'myrefrence-499b0.firebasestorage.app',
  );
}
